# Generated by Django 5.1.3 on 2024-11-19 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0004_rename_social_yandex_engineer_social_website_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='all_info',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='education',
            field=models.CharField(blank=True, max_length=200, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='engineer',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='engineer_image',
            field=models.ImageField(default='repairs/engineer.jpeg', upload_to='repairs/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='i_info',
            field=models.TextField(blank=True, max_length=100, verbose_name='Кратко'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='price',
            field=models.FileField(default='repairs/price_repair_cleaner.jpeg', upload_to='repairs/', verbose_name='Цены'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='social_telegram',
            field=models.CharField(blank=True, max_length=200, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='social_vkontakte',
            field=models.CharField(blank=True, max_length=200, verbose_name='Вконтакте'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='social_website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='social_whatsapp',
            field=models.CharField(blank=True, max_length=200, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='username',
            field=models.CharField(blank=True, max_length=200, verbose_name='Username'),
        ),
    ]
